[build]
  # Build command using Bun
  command = "curl -fsSL https://bun.sh/install | bash && export PATH=\"$HOME/.bun/bin:$PATH\" && bun install && bun run build"
  
  # Directory to publish (where the static files are located after build)
  publish = "out"

[build.environment]
  # Node.js version (Bun requires Node 18+)
  NODE_VERSION = "18"
  
  # Use Bun as package manager
  NPM_FLAGS = "--version" # This forces Netlify to not use npm
  
  # Skip ESLint during build (since we configured it)
  SKIP_LINT = "true"
  
  # Enable Next.js telemetry (optional)
  NEXT_TELEMETRY_DISABLED = "1"

# Note: Redirects are handled by public/_redirects file

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings (if you have any API routes)
[functions]
  directory = "netlify/functions"

# Development settings
[dev]
  command = "bun dev"
  port = 3000
